services:
  graph_db:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./conf:/var/lib/neo4j/conf
      - ./data:/data
      - ./import:/import
      - ./logs:/logs
      - ./plugins:/plugins
    environment:
      NEO4J_AUTH: none
      NEO4J_dbms_memory_heap_max__size: 3000m
      NEO4J_dbms_memory_pagecache_size: 1000m
      NEO4J_dbms_security_procedures_unrestricted: gds.*

